export const EVENTS = {
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_UPDATED: "ORDER_UPDATED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  KITCHEN_TICKET_CREATED: "KITCHEN_TICKET_CREATED",
  KITCHEN_TICKET_UPDATED: "KITCHEN_TICKET_UPDATED",
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  WAITER_CALL_CREATED: "WAITER_CALL_CREATED",
  WAITER_CALL_ACKNOWLEDGED: "WAITER_CALL_ACKNOWLEDGED",
  WAITER_CALL_RESOLVED: "WAITER_CALL_RESOLVED",
  NOTIFICATION: "NOTIFICATION",
} as const;
